import QueryWrapper from './auth/QueryWrapper'




export const metadata = {
  title: 'OVS Willing Workers',
  description: 'Generated by create next app',
}

// const store = configureStore({
//   reducer: rootReducer,
//   // Other options...
// });


export default  function RootLayout({ children, }: {
  children: any;
}) {
  
  return (
    
    <html lang="en">
      <head>
        {/* Your head content here */}
      </head>

      <body>
      
          <QueryWrapper>
            {children}
          </QueryWrapper>
     
   
      </body>
   
    </html>
  )
}
