
import QueryWrapper from './auth/QueryWrapper'
import { Footer } from './Footer'
import './globals.css'
import Nav from './Nav'

export const metadata = {
  title: 'OVS Willing Workers',
  description: 'Generated by create next app',
}



export default function RootLayout({ children, }: {
  children: any;
}) {
  return (
    <html lang="en">

      <body>
  
      <QueryWrapper>

 

        {children}
      
            </QueryWrapper>

        
       
       
        </body>
   
    </html>
  )
}
